algoritmo "13. NOVO SALARIO"
var
  sal, novosal, calcsal: real
inicio
      escreva ("Digite o salário do funcionário: R$")
      leia (sal)
      calcsal <- sal * 0.15
      novosal <- sal + calcsal
      escreval ("O novo salário do funcionário com o aumento é de R$ ", novosal)

fimalgoritmo

13) Faça um algoritmo que leia o salário de um funcionário, calcule e mostre o
seu novo salário, com 15% de aumento.