algoritmo "26.LEITURADENUMS"
var
    n1,n2:inteiro
inicio
      escreva("Digite o primeiro número: ")
      leia (n1)
      escreva ("Digite o segundo número: ")
      leia (n2)
      se (n1 > n2) entao
         escreval ("O primeiro valor é o maior.")
      fimse
      se (n2>n1) entao
         escreval ("O segundo valor é o maior.")
      fimse
      se (n1=n2) entao
         escreval ("Não existe valor maior, os dois são iguais.")
      fimse
      

fimalgoritmo